name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v7
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: dist\/.*|\.github\/workflows\/[^\/]+\.yml|README\.md|github_conf\/.*
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_CHECKOV: false
